[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
game_escrow = "9KqSa63Un4ZSge7RquC76yNRVetu2gaWD7VLDwwczsTs"

[programs.mainnet]
game_escrow = "9KqSa63Un4ZSge7RquC76yNRVetu2gaWD7VLDwwczsTs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --manifest-path programs/game-escrow/Cargo.toml"
